version: '3.8'

services:
  ai-image-classifier:
    build: .
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for SSL termination
  # nginx-proxy:
  #   image: nginx:alpine
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./ssl:/etc/nginx/ssl
  #     - ./proxy.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - ai-image-classifier